name: Lab1
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "first step"
      - name: step2
        run: echo "second step"
